export { default as CollapsIcon } from "./CollapsIcon";
export { default as DashboardIcon } from "./Dashboard";
export { default as MonitoringIcon } from "./Monitoring";
export { default as LogoIcon } from "./Logo";
export { default as TemplateIcon } from "./Template";
export { default as UserIcon } from "./User";
export { default as RequestIcon } from "./Request";
export { default as ArrowIcon } from "./ArrowIcon";
export { default as PasswordIcon } from "./Password";
export { default as ErrorIcon } from "./ErroIcon";
export { default as SuccessIcon } from "./SuccessIcon"
export { default as BackLogo } from "./BackLogo"
export { default as BackArrow } from "./BackArrow"
export { default as DeleteLogo } from "./DeleteLogo"
export { default as HorizontalLines } from "./HorizontalLines"
export { default as PenLogo } from "./PenLogo"
export { default as PlusLogo } from "./PlusLogo"
export { default as CloseSquare } from "./CloseSquare";
export { default as PlusSquare } from "./PlusSquare";
export { default as MinusSquare } from "./MinusSquare";
export { default as EditIcon } from "./EditIcon";
export { default as UploadLogo } from "./UploadLogo"
export { default as ActionLogo } from "./ActionLogo"
export { default as CorrectIcon } from "./CorrectIcon"
export { default as EyeLogo } from "./EyeLogo"