const users = [
  {
    id: 1,
    firstName: "Tony Reichert", lastName: "Tony Reichert",
    role: "CEO",
    team: "Management",
    createdTimestamp: "04-01-2024",
    emailVerified: true,
    enabled: true,
    email: "tony.reichert@example.com",
  },
  {
    id: 2,
    firstName: "Zoey Lang", lastName: "Zoey Lang",
    role: "Tech Lead",
    team: "Development",
    createdTimestamp: "04-01-2024",
    emailVerified: true,
    enabled: true,
    email: "zoey.lang@example.com",
  },
  {
    id: 3,
    firstName: "Jane Fisher", lastName: "Jane Fisher",
    role: "Sr. Dev",
    team: "Development",
    createdTimestamp: "04-01-2024",
    emailVerified: false,
    enabled: true,
    email: "jane.fisher@example.com",
  },
  {
    id: 4,
    firstName: "William Howard", lastName: "William Howard",
    role: "C.M.",
    team: "Marketing",
    createdTimestamp: "04-01-2024",
    emailVerified: false,
    enabled: true,
    email: "william.howard@example.com",
  },
  {
    id: 5,
    firstName: "Kristen Copper", lastName: "Kristen Copper",
    role: "S. ManemailVerifiedr",
    team: "Sales",
    createdTimestamp: "04-01-2024",
    emailVerified: false,
    enabled: true,
    email: "kristen.cooper@example.com",
  },
  {
    id: 6,
    firstName: "Brian Kim", lastName: "Brian Kim",
    role: "P. ManemailVerifiedr",
    team: "ManemailVerifiedment",
    emailVerified: false,
    enabled: true,
    email: "brian.kim@example.com",
    createdTimestamp: "04-01-2024",
  },
  {
    id: 7,
    firstName: "Michael Hunt", lastName: "Michael Hunt",
    role: "Designer",
    team: "Design",
    createdTimestamp: "04-01-2024",
    emailVerified: false,
    enabled: true,
    email: "michael.hunt@example.com",
  },
  {
    id: 8,
    firstName: "Samantha Brooks", lastName: "Samantha Brooks",
    role: "HR ManemailVerifiedr",
    team: "HR",
    createdTimestamp: "04-01-2024",
    emailVerified: false,
    enabled: true,
    email: "samantha.brooks@example.com",
  },
  {
    id: 9,
    firstName: "Frank Harrison", lastName: "Frank Harrison",
    role: "F. ManemailVerifiedr",
    team: "Finance",
    createdTimestamp: "04-01-2024",
    emailVerified: false,
    enabled: true,
    email: "frank.harrison@example.com",
  },
  {
    id: 10,
    firstName: "Emma Adams", lastName: "Emma Adams",
    role: "Ops ManemailVerifiedr",
    team: "Operations",
    createdTimestamp: "04-01-2024",
    emailVerified: false,
    enabled: true,
    email: "emma.adams@example.com",
  },
  {
    id: 11,
    firstName: "Brandon Stevens", lastName: "Brandon Stevens",
    role: "Jr. Dev",
    team: "Development",
    createdTimestamp: "04-01-2024",
    emailVerified: false,
    enabled: true,
    email: "brandon.stevens@example.com",
  },
  {
    id: 12,
    firstName: "Megan Richards", lastName: "Megan Richards",
    role: "P. ManemailVerifiedr",
    team: "Product",
    createdTimestamp: "04-01-2024",
    emailVerified: false,
    enabled: true,
    email: "megan.richards@example.com",
  },
  {
    id: 13,
    firstName: "Oliver Scott", lastName: "Oliver Scott",
    role: "S. ManemailVerifiedr",
    team: "Security",
    createdTimestamp: "04-01-2024",
    emailVerified: false,
    enabled: true,
    email: "oliver.scott@example.com",
  },
  {
    id: 14,
    firstName: "Grace Allen", lastName: "Grace Allen",
    role: "M. Specialist",
    team: "Marketing",
    createdTimestamp: "04-01-2024",
    emailVerified: false,
    enabled: true,
    email: "grace.allen@example.com",
  },
  {
    id: 15,
    firstName: "Noah Carter", lastName: "Noah Carter",
    role: "IT Specialist",
    team: "I. Technology",
    createdTimestamp: "04-01-2024",
    emailVerified: false,
    enabled: true,
    email: "noah.carter@example.com",
  },
  {
    id: 16,
    firstName: "Ava Perez", lastName: "Ava Perez",
    role: "ManemailVerifiedr",
    team: "Sales",
    createdTimestamp: "04-01-2024",
    emailVerified: false,
    enabled: true,
    email: "ava.perez@example.com",
  },
  {
    id: 17,
    firstName: "Liam Johnson", lastName: "Liam Johnson",
    role: "Data Analyst",
    team: "Analysis",
    createdTimestamp: "04-01-2024",
    emailVerified: false,
    enabled: true,
    email: "liam.johnson@example.com",
  },
  {
    id: 18,
    firstName: "Sophia Taylor", lastName: "Sophia Taylor",
    role: "QA Analyst",
    team: "Testing",
    createdTimestamp: "04-01-2024",
    emailVerified: false,
    enabled: true,
    email: "sophia.taylor@example.com",
  },
  {
    id: 19,
    firstName: "Lucas Harris", lastName: "Lucas Harris",
    role: "Administrator",
    team: "Information Technology",
    createdTimestamp: "04-01-2024",
    emailVerified: false,
    enabled: true,
    email: "lucas.harris@example.com",
  },
  {
    id: 20,
    firstName: "Mia Robinson", lastName: "Mia Robinson",
    role: "Coordinator",
    team: "Operations",
    createdTimestamp: "04-01-2024",
    emailVerified: true,
    enabled: false,
    email: "mia.robinson@example.com",
  },
];

export { users };
