apiVersion: v1
kind: Service
metadata:
  name: platform-ui-v1
  namespace: ui
spec:
  type: NodePort
  selector:
    app: platform-ui-v1
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30727
      
      
 